import { create } from 'zustand';

const THEMES = [
    { left: "Pauvre", right: "Riche" },
    { left: "Petit", right: "Grand" },
    { left: "Doux", right: "Violent" },
    { left: "Nul en cuisine", right: "Chef étoilé" },
    { left: "Faible", right: "Musclé" },
    { left: "Lente", right: "Rapide" },
    { left: "Timide", right: "Confiant" },
    { left: "Naïf", right: "Parano" },
    { left: "Sale", right: "Propre" },
    { left: "Calme", right: "Explosif" },
    { left: "Froid", right: "Chaud" },
    { left: "Triste", right: "Heureux" },
    { left: "Vieillot", right: "Futuriste" },
    { left: "Délicat", right: "Robuste" },
    { left: "Fragile", right: "Indestructible" },
    { left: "Inutile", right: "Essentiel" },
    { left: "Discret", right: "Tape-à-l’œil" },
    { left: "Ennuyant", right: "Passionnant" },
    { left: "Irréel", right: "Hyper réaliste" },
    { left: "Sobre", right: "Déjanté" },
    { left: "Économique", right: "Luxueux" },
    { left: "Sain", right: "Catastrophique pour la santé" },
    { left: "Minuscule", right: "Immense" },
    { left: "Simple", right: "Ultra complexe" },
    { left: "Basique", right: "Classe" },
    { left: "Zéro confiance", right: "Confiance totale" },
    { left: "Fade", right: "Épicé" },
    { left: "Mou", right: "Dur" },
    { left: "Faible", right: "Monstrueusement puissant" },
    { left: "Ennuyeux", right: "Hilarant" },
    { left: "Débutant", right: "Expert" },
    { left: "Ringard", right: "Stylé" },
    { left: "Inoffensif", right: "Dangereux" },
    { left: "Confus", right: "Clair" },
    { left: "Bas bruit", right: "Très bruyant" },
    { left: "Léger", right: "Lourd" },
    { left: "Peu motivé", right: "Surmotivé" },
    { left: "Flemmard", right: "Productif" },
    { left: "Peu connu", right: "Ultra connu" },
    { left: "Petit risque", right: "Gros risque" },
    { left: "Plat", right: "Montagneux" },
    { left: "Alcool faible", right: "Alcool fort" },
    { left: "Zéro hype", right: "Maxi hype" },
    { left: "Peu romantique", right: "Ultra romantique" },
    { left: "Bas budget", right: "Hors de prix" },
    { left: "Peu stimulant", right: "Très stimulant" },
    { left: "Hypo sucré", right: "Hyper sucré" },
    { left: "Sans goût", right: "Explosion de saveur" },
    { left: "Normal", right: "Complètement fou" },
    { left: "Invisible", right: "Visible" },
    { left: "Peu organisé", right: "Très organisé" },
    { left: "Introverti", right: "Extraverti" },
    { left: "Impoli", right: "Hyper poli" },
    { left: "Ancien", right: "Moderne" },
    { left: "Minimaliste", right: "Maximaliste" },
    { left: "Pas stressant", right: "Ultra stressant" },
    { left: "Zéro ambiance", right: "Ambiance énorme" },
    { left: "Moelleux", right: "Croquant" },
    { left: "Zéro énergie", right: "Plein d’énergie" },
    { left: "Peu responsable", right: "Très responsable" },
    { left: "Court", right: "Très long" },
    { left: "Peu fiable", right: "Très fiable" },
    { left: "Simple", right: "Technique" },
    { left: "Faible intensité", right: "Haute intensité" },
    { left: "Plat", right: "Dramatique" },
    { left: "Peu effrayant", right: "Terrifiant" },
    { left: "Petit bruit", right: "Grosse explosion" },
    { left: "Pas addictif", right: "Ultra addictif" },
    { left: "Peu rare", right: "Très rare" },
    { left: "Peu précis", right: "Chirurgical" },
    { left: "Peu cher", right: "Hors de prix" },
    { left: "Peu recherché", right: "Très recherché" },
    { left: "Pas tendance", right: "Très tendance" },
    { left: "Pas jaloux", right: "Ultra jaloux" },
    { left: "Peu spicy", right: "Dragon spicy" },
    { left: "Peu flexible", right: "Très flexible" },
    { left: "Loin", right: "Très proche" },
    { left: "Peu gourmand", right: "Très gourmand" },
    { left: "Peu câlin", right: "Très câlin" },
    { left: "Petit impact", right: "Gros impact" },
    { left: "Peu magique", right: "Très magique" },
    { left: "Bas volume", right: "Très fort" },
    { left: "Désert", right: "Jungle" },
    { left: "Mouillé", right: "Sec" },
    { left: "Peu réaliste", right: "Très réaliste" },
    { left: "Peu exotique", right: "Très exotique" },
    { left: "Peu parfumé", right: "Très parfumé" },
    { left: "Peu dramatique", right: "Ultra dramatique" },
    { left: "Sobre", right: "Trash" },
    { left: "Peu dangereux", right: "Mortel" },
    { left: "Peu aventureux", right: "Très aventureux" },
    { left: "Bas QI", right: "Haut QI" },
    { left: "Peu lumineux", right: "Très lumineux" },
    { left: "Peu visible", right: "Flashy" },
    { left: "Court terme", right: "Long terme" },
    { left: "Peu profond", right: "Très profond" },
    { left: "Petit bruit", right: "Éruption volcanique" },
    { left: "Peu fiable", right: "Ultra fiable" },
    { left: "Peu sociable", right: "Très sociable" },
    { left: "Pas sportif", right: "Très sportif" },
    { left: "Peu stratégique", right: "Ultra stratégique" },
    { left: "Dégueu", right: "Délicieux" },
    { left: "Peu drôle", right: "Hilarant" },
    { left: "Boring", right: "Épique" },
    { left: "Peu technologique", right: "Très technologique" },
    { left: "Bas niveau", right: "Haut niveau" },
    { left: "Petit volume", right: "Subwoofer mode" },
    { left: "Peu toxique", right: "Très toxique" },
    { left: "Peu sexy", right: "Très sexy" },
    { left: "Peu ambitieux", right: "Très ambitieux" },
    { left: "Pas épique", right: "Totalement épique" },
    { left: "Petit confort", right: "Confort ultime" },
    { left: "Peu intense", right: "Ultra intense" },
    { left: "Peu mystérieux", right: "Énigmatique" },
    { left: "Bas budget", right: "Carte black" },
    { left: "Peu dangereux", right: "Haute tension" },
    { left: "Sans style", right: "Over stylé" },
    { left: "Peu curieux", right: "Très curieux" },
    { left: "Petit frisson", right: "Grosse adrénaline" },
    { left: "Peu spicy", right: "Boucherie mexicaine" },
    { left: "Peu attachant", right: "Très attachant" },
    { left: "Léger", right: "Tank" },
    { left: "Peu mignon", right: "Ultra cute" },
    { left: "Peu rare", right: "Légendaire" },
    { left: "Petit ego", right: "Égo démesuré" },
    { left: "Peu philosophique", right: "Très philosophique" },
    { left: "Simple", right: "Esprit 4D" },
    { left: "Petit chaos", right: "Apocalypse" },
    { left: "Peu social", right: "Très social" },
    { left: "Peu mature", right: "Très mature" },
    { left: "Zéro vibe", right: "Max vibe" },
    { left: "Peu beau", right: "Très beau" },
    { left: "Petit mystère", right: "Enigme totale" },
    { left: "Peu nerveux", right: "Ultra nerveux" },
    { left: "Peu motivant", right: "Ultra motivant" },
    { left: "Peu sucré", right: "Candyland" },
    { left: "Bas IQ chocolat", right: "100% cacao" },
    { left: "Petit fun", right: "Full fun" },
    { left: "Peu impactant", right: "Révolutionnaire" },
    { left: "Peu magique", right: "Sorcellerie" },
    { left: "Léger", right: "Atomique" },
    { left: "Calme", right: "Chaotique" },
    { left: "Peu random", right: "Très random" },
    { left: "Peu épique", right: "Mythique" },
    { left: "Petit délire", right: "Grosse dinguerie" },
    { left: "Peu crédible", right: "Très crédible" },
    { left: "Peu connu", right: "Iconique" },
    { left: "Peu dangereux", right: "On risque sa vie" },
    { left: "Pas stylé", right: "Ultra stylé" },
    { left: "Sans émotion", right: "Hyper émotif" },
    { left: "Peu inspirant", right: "Très inspirant" },
    { left: "Petit talent", right: "Très talentueux" },
    { left: "Peu classe", right: "Ultra classe" },
    { left: "Petit pouvoir", right: "Pouvoir cosmique" },
    { left: "Léger humour", right: "Fou rire" },
    { left: "Peu créatif", right: "Génie créatif" },
    { left: "Peu vintage", right: "Ultra vintage" },
    { left: "Peu bruyant", right: "Concert métal" },
    { left: "Peu sucré", right: "Ultra sucré" },
    { left: "Peu salé", right: "Mer Morte" },
    { left: "Peu piquant", right: "Feu de l’enfer" },
    { left: "Peu fragile", right: "Incassable" },
    { left: "Peu romantique", right: "Hollywood" },
    { left: "Petit drama", right: "Télénovela" },
    { left: "Peur faible", right: "Panique totale" },
    { left: "Peu lumineux", right: "Soleil" },
    { left: "Faible", right: "Surpuissant" },
    { left: "Petit flow", right: "Flow légendaire" },
    { left: "Peu parfumé", right: "Nuage de parfum" },
    { left: "Peu énergique", right: "Tornade" },
    { left: "Zéro swag", right: "Top swag" },
    { left: "Léger humour", right: "One-man show" },
    { left: "Peu marrant", right: "Mort de rire" },
    { left: "Peu social", right: "Influenceur" },
    { left: "Petit budget", right: "Limousine" },
    { left: "Peu sale", right: "Très sale" },
    { left: "Peu clean", right: "Chirurgical" },
    { left: "Peu alcoolisé", right: "Très alcoolisé" },
    { left: "Petit volume", right: "Explosion nucléaire" },
    { left: "Peu organisé", right: "Maître Feng Shui" },
    { left: "Petit appétit", right: "Ogre" },
    { left: "Peu connecté", right: "Cyborg" },
    { left: "Bas niveau", right: "Overlevel" },
    { left: "Peu dangereux", right: "Extrême" },
    { left: "Peu épicé", right: "Volcano mode" },
    { left: "Petit fun", right: "Full carnaval" },
    { left: "Peu stylé", right: "Haute couture" },
    { left: "Peu rare", right: "Collector" },
    { left: "Sans humour", right: "Humoriste pro" },
    { left: "Peu compact", right: "XXL" },
    { left: "Peu solide", right: "Indestructible" },
    { left: "Peu ambitieux", right: "Visionnaire" },
    { left: "Petit confort", right: "Boutique hotel" },
    { left: "Pas intense", right: "Brutal" },
    { left: "Peu précis", right: "Sniper" },
    { left: "Petit ego", right: "Kanye West" },
    { left: "Peu fragile", right: "Vitres blindées" },
    { left: "Peu fun", right: "Fiesta totale" },
    { left: "Pas magique", right: "Wizard mode" },
    { left: "Petit bonheur", right: "Bonheur ultime" }
];
const useGameStore = create((set) => ({
    gameState: 'HOME', // HOME, LOBBY, PLAYING
    gamePhase: 'THINKING', // THINKING, GUESSING, REVEAL
    gameMode: 'ONLINE', // ONLINE, OFFLINE

    isHost: false,
    roomCode: null,
    nickname: '',
    players: [],

    // Game Data
    theme: THEMES[0],
    targetValue: 50, // 0-100
    clue: '',
    sliderValue: 50,
    skipsRemaining: 2,

    // Actions
    setNickname: (name) => set({ nickname: name }),
    createRoom: () => set((state) => ({
        gameState: 'LOBBY',
        gameMode: 'ONLINE',
        isHost: true,
        roomCode: Math.random().toString(36).substring(2, 6).toUpperCase(),
        players: [{ name: state.nickname || 'Host', id: 1 }]
    })),
    joinRoom: (code) => set((state) => ({
        gameState: 'LOBBY',
        gameMode: 'ONLINE',
        isHost: false,
        roomCode: code,
        players: [{ name: 'Host', id: 1 }, { name: state.nickname || 'Guest', id: 2 }]
    })),
    startGame: () => set({
        gameState: 'PLAYING',
        gamePhase: 'THINKING',
        theme: THEMES[Math.floor(Math.random() * THEMES.length)],
        targetValue: Math.random() * 100,
        skipsRemaining: 2
    }),
    startOfflineGame: () => set({
        gameState: 'PLAYING',
        gameMode: 'OFFLINE',
        gamePhase: 'THINKING',
        theme: THEMES[Math.floor(Math.random() * THEMES.length)],
        targetValue: Math.random() * 100,
        players: [{ name: 'Players', id: 1 }],
        skipsRemaining: 2
    }),
    submitClue: (clue) => set({ clue, gamePhase: 'GUESSING' }),
    submitGuess: () => set({ gamePhase: 'REVEAL' }),
    nextRound: () => set({
        gamePhase: 'THINKING',
        clue: '',
        targetValue: Math.random() * 100,
        sliderValue: 50,
        theme: THEMES[Math.floor(Math.random() * THEMES.length)],
        skipsRemaining: 2
    }),
    skipTheme: () => set((state) => {
        if (state.skipsRemaining > 0) {
            return {
                theme: THEMES[Math.floor(Math.random() * THEMES.length)],
                skipsRemaining: state.skipsRemaining - 1
            };
        }
        return state;
    }),
    setSliderValue: (val) => set({ sliderValue: val }),
}));

export default useGameStore;
